name: Automatically create release with artifact on pull request

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # set up jdk 1.8
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # build jar with maven
      - run: mvn --batch-mode --update-snapshots verify

      # create release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload previously created jar to release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/ezAuctions*.jar
          asset_name: ezAuctions.jar
          asset_content_type: application/java-archive
