name: Java CI with Maven & Artifact Build

on:
  push:
    branches: [ '**', '!master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: mvn --batch-mode --update-snapshots verify
    - uses: actions/upload-artifact@v2
      with:
        path: target/ezAuctions*.jar
